-- Feature 21: Pricing & Margin Optimization (Phase 4)
-- Dynamic pricing models, margin analysis, price waterfall, and optimization recommendations

CREATE TABLE IF NOT EXISTS pricing_models (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  model_type TEXT NOT NULL DEFAULT 'cost_plus',
  status TEXT NOT NULL DEFAULT 'draft',
  product_id TEXT,
  product_name TEXT,
  category TEXT,
  brand TEXT,
  customer_id TEXT,
  customer_name TEXT,
  channel TEXT,
  region TEXT,
  base_cost REAL DEFAULT 0,
  target_margin_pct REAL DEFAULT 0,
  list_price REAL DEFAULT 0,
  net_price REAL DEFAULT 0,
  floor_price REAL DEFAULT 0,
  ceiling_price REAL DEFAULT 0,
  current_price REAL DEFAULT 0,
  recommended_price REAL DEFAULT 0,
  price_elasticity REAL DEFAULT 0,
  volume_sensitivity REAL DEFAULT 0,
  competitor_avg_price REAL DEFAULT 0,
  market_position TEXT DEFAULT 'parity',
  currency TEXT DEFAULT 'ZAR',
  effective_date TEXT,
  end_date TEXT,
  last_optimized_at TEXT,
  optimization_score REAL DEFAULT 0,
  confidence_score REAL DEFAULT 0,
  owner TEXT,
  approved_by TEXT,
  approved_at TEXT,
  created_by TEXT,
  tags TEXT DEFAULT '[]',
  notes TEXT,
  data TEXT DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS margin_analyses (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  analysis_type TEXT NOT NULL DEFAULT 'product_margin',
  status TEXT NOT NULL DEFAULT 'active',
  dimension TEXT DEFAULT 'product',
  product_id TEXT,
  product_name TEXT,
  category TEXT,
  brand TEXT,
  customer_id TEXT,
  customer_name TEXT,
  channel TEXT,
  region TEXT,
  period_start TEXT,
  period_end TEXT,
  gross_sales REAL DEFAULT 0,
  trade_spend REAL DEFAULT 0,
  net_sales REAL DEFAULT 0,
  cogs REAL DEFAULT 0,
  gross_profit REAL DEFAULT 0,
  gross_margin_pct REAL DEFAULT 0,
  trade_margin_pct REAL DEFAULT 0,
  net_margin_pct REAL DEFAULT 0,
  contribution_margin REAL DEFAULT 0,
  contribution_margin_pct REAL DEFAULT 0,
  operating_margin REAL DEFAULT 0,
  operating_margin_pct REAL DEFAULT 0,
  volume REAL DEFAULT 0,
  avg_selling_price REAL DEFAULT 0,
  avg_cost REAL DEFAULT 0,
  margin_trend TEXT DEFAULT 'stable',
  margin_vs_target REAL DEFAULT 0,
  target_margin_pct REAL DEFAULT 0,
  improvement_opportunity REAL DEFAULT 0,
  created_by TEXT,
  notes TEXT,
  data TEXT DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS price_waterfall_items (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL,
  analysis_id TEXT,
  pricing_model_id TEXT,
  product_id TEXT,
  product_name TEXT,
  customer_id TEXT,
  customer_name TEXT,
  period TEXT,
  step_order INTEGER DEFAULT 0,
  step_name TEXT NOT NULL,
  step_type TEXT DEFAULT 'deduction',
  amount REAL DEFAULT 0,
  pct_of_list REAL DEFAULT 0,
  running_total REAL DEFAULT 0,
  running_margin_pct REAL DEFAULT 0,
  benchmark_amount REAL DEFAULT 0,
  variance REAL DEFAULT 0,
  notes TEXT,
  data TEXT DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS pricing_recommendations (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL,
  model_id TEXT,
  recommendation_type TEXT DEFAULT 'price_increase',
  priority TEXT DEFAULT 'medium',
  status TEXT NOT NULL DEFAULT 'pending',
  product_id TEXT,
  product_name TEXT,
  customer_id TEXT,
  customer_name TEXT,
  channel TEXT,
  current_price REAL DEFAULT 0,
  recommended_price REAL DEFAULT 0,
  price_change_pct REAL DEFAULT 0,
  current_margin_pct REAL DEFAULT 0,
  projected_margin_pct REAL DEFAULT 0,
  revenue_impact REAL DEFAULT 0,
  margin_impact REAL DEFAULT 0,
  volume_impact_pct REAL DEFAULT 0,
  confidence_score REAL DEFAULT 0,
  risk_level TEXT DEFAULT 'low',
  rationale TEXT,
  action_taken TEXT,
  applied_at TEXT,
  applied_by TEXT,
  created_by TEXT,
  notes TEXT,
  data TEXT DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_pricing_models_company ON pricing_models(company_id);
CREATE INDEX IF NOT EXISTS idx_pricing_models_status ON pricing_models(company_id, status);
CREATE INDEX IF NOT EXISTS idx_margin_analyses_company ON margin_analyses(company_id);
CREATE INDEX IF NOT EXISTS idx_margin_analyses_type ON margin_analyses(company_id, analysis_type);
CREATE INDEX IF NOT EXISTS idx_price_waterfall_company ON price_waterfall_items(company_id);
CREATE INDEX IF NOT EXISTS idx_price_waterfall_analysis ON price_waterfall_items(analysis_id);
CREATE INDEX IF NOT EXISTS idx_pricing_recommendations_company ON pricing_recommendations(company_id);
CREATE INDEX IF NOT EXISTS idx_pricing_recommendations_model ON pricing_recommendations(model_id);
